package p;
import Controlador.IControlador;
import Modelo.BackJack;
import Modelo.IJuego;
import Vista.IVista;
import Vista.VistaConsola;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucci
 */
public class Intrucciones extends javax.swing.JFrame {

    private IControlador controlador;
    private Lobby lobby;
    /**
     * Creates new form Intrucciones
     */
    public Intrucciones(Lobby volver) {
        //No modificar el tamaño de la ventana:
        this.setResizable(false);
        lobby = volver;
        initComponents();
        this.setLocationRelativeTo(null);
        this.textArea1.setText("Objetivo del Juego\n" +
"Vencer al Crupier: Tu objetivo es tener un valor de mano superior al del crupier sin exceder 21.\n" +
"Evitar Pasarse: Si tu mano supera 21, te \"pasas\" y automáticamente pierdes la ronda.\n" +
"Blackjack: Conseguir un valor de mano de 21 con tus dos primeras cartas (un As y una carta de valor 10) se llama \"blackjack\" y usualmente paga extra.\n" +
"Valores de las Cartas\n" +
"Cartas Numéricas (2-10): Valen su valor nominal.\n" +
"Figuras (Jota, Reina, Rey): Cada una vale 10 puntos.\n" +
"Ases: Pueden valer 1 o 11 puntos, dependiendo de cuál valor beneficie más a tu mano.\n" +
"Descripción general del juego\n" +
"Realiza Tu Apuesta\n" +
"Antes de que se repartan las cartas, coloca tu apuesta en el área designada para apuestas en la mesa.\n" +
"Reparto Inicial\n" +
"Jugadores: Cada jugador recibe dos cartas, generalmente repartidas boca arriba.\n" +
"Crupier: Recibe dos cartas: una boca arriba (la \"carta abierta\") y una boca abajo (la \"carta oculta\").\n" +
"Decisiones del Jugador\n" +
"Comenzando desde la izquierda del crupier, cada jugador decide cómo jugar su mano:\n" +
"Pedir: Tomar otra carta para aumentar el valor de tu mano.\n" +
"Plantarse: Mantener tu mano actual y terminar tu turno.\n" +
"Doblar:\n" +
"Duplicar tu apuesta inicial.\n" +
"Recibir exactamente una carta más.\n" +
"Se usa mejor cuando crees que una carta más te dará una mano fuerte.\n" +
"Dividir:\n" +
"Si tus dos primeras cartas son del mismo valor (p. ej., dos 8), puedes dividirlas en dos manos separadas.\n" +
"Debes hacer una apuesta adicional igual a tu apuesta original para la nueva mano.\n" +
"Juega cada mano por separado.\n" +
"Rendirse (si está permitido):\n" +
"Renuncia a la mitad de tu apuesta para terminar tu participación en la ronda.\n" +
"Útil cuando crees que tienes pocas posibilidades de ganar contra la carta abierta del crupier.\n" +
"Turno del Crupier\n" +
"Después de que todos los jugadores hayan terminado, el crupier revela su carta oculta.\n" +
"Reglas del Crupier:\n" +
"Debe pedir hasta que su mano sume 17 o más.\n" +
"En algunos casinos, el crupier debe pedir con un \"17 suave\" (una mano que suma 17 con un As contado como 11).\n" +
"Resultado\n" +
"Ganar: Tu mano es más alta que la del crupier sin pasarte.\n" +
"Perder: Tu mano es menor que la del crupier o te pasas.\n" +
"Empate: Tu mano es igual a la del crupier; tu apuesta es devuelta.\n" +
"Pago de Blackjack: Usualmente paga 3:2, lo que significa que ganas $15 por una apuesta de $10...");
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textArea1 = new java.awt.TextArea();
        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textArea1.setFont(new java.awt.Font("Blackadder ITC", 0, 12)); // NOI18N
        jPanel1.add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 630, 330));

        button1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        button1.setLabel("< Menu Principal");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p/mesa3.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
       // Lobby lb = new Lobby(controlador);
        lobby.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
