package p;

import Controlador.Controlador;
import Controlador.IControlador;
import Vista.IVista;

import javax.swing.*;
import java.util.List;
import java.util.function.Consumer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucci
 */
public class Lobby extends javax.swing.JFrame implements IVista {

    private Controlador controlador;

    /**
     * Creates new form Lobby
     */
    public Lobby() {
        //Cargo imagnes
        initComponents();
        //Localizamos la ventana en el centro de la pantalla.
        this.setLocationRelativeTo(null);
       // this.controlador = controlador;
       // this.controlador.setVista(this);
       // controlador.setVista(this);
        this.setLocationRelativeTo(null);
     //   this.controlador.setVista(this);
     //   controlador.setVista(this);
        //No modificar el tamaño de la ventana:
        this.setResizable(false);
        Iniciar();
        jLabel2.setText("Bienvenido");
    }

    public IControlador getControlador() {
        return controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BlackJack Argentino");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LAS - @Copyrigth 2025");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 180, 30));

        button1.setLabel("JUGAR");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel2.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 290, 40));

        button3.setLabel("RANING");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel2.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 290, 40));

        button4.setLabel("INSTRUCCIONES");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel2.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 290, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Imagenes/mesa3.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -250, 1470, 1100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:

        //voy a pedir el nombre del jugador:
        String nombre_Jugador = JOptionPane.showInputDialog(this, "Ingrese Su nombre: ");

        if (nombre_Jugador != null && !nombre_Jugador.trim().isEmpty()) {
            VistaPartida a = new VistaPartida();
            controlador.setVista(a);
            System.out.println("el nombre del jugador es : " +  nombre_Jugador);
            a.setControlador(controlador);//aca estaria guarda el controlador.
            a.setVisible(true);
            //Le paso el nombre del jugador a la ventana a la ventan.

            controlador.setNombreJugador(nombre_Jugador);
            a.setMi_Nombre(nombre_Jugador);
            // controlador.iniciarJuego();
            this.setVisible(false);
            controlador.iniciarJuego();
        }
        else {
            JOptionPane.showInputDialog(this, "Debe Ingresar un nombre Valido");
        }


        //-------------------------- iNICIAL LA CONSOLITA CON EL JEUEGO.
        /* ...
        IJuego juego = new BackJack();
        IControlador controlador = new Controlador(juego);
        IVista vista = new VistaConsola(controlador);
        vista.Iniciar();

         */

    }
//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        Ranking ranking = new Ranking(this);
        ranking.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        Intrucciones intru = new Intrucciones(this);
        intru.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button4ActionPerformed

    /**
     * @param args the command line arguments
     */
    //El main de Lobby

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Iniciar() {
        this.setVisible(true);
       // controlador.iniciarJuego();
    }


    /*
    @Override
    public void setControlador(Controlador.IControlador controlador) {
        this.controlador = controlador;
    }

     */

    @Override
    public void mostrarMensaje(String Mensaje) {
        System.out.println("Entro en lobby la repuytisma");
    }

    @Override
    public void mostrarCartasMazo(String mostrarMazo, int cantidad) {

    }

    @Override
    public void mostrarSaldo(String jugador, float saldo) {
       // label2.setText(String.valueOf(saldo));
      
        
    }

    @Override
    public float pedirApuesta() {
        return 0;
    }

    @Override
    public void actualizarTurno(String JugadorActual, float saldoDelJugador){

    }

    @Override
    public int pedirOpcion(String mensaje) {

        return 0;
    }

    @Override
    public void mostrarCartas(int cartasJugador, int cartasCrupier) {

    }

    @Override
    public void mostrarApuesta(float apuesta) {

    }

    @Override
    public void mostrarCartasSoloJugador(int cartasJugador) {

    }

    @Override
    public void mostrarManoJugador(String manoDeJugador, List<String> ruta, String cartaCrupier) {

    }

    @Override
    public void mostrarManoJugadores(String manoDeJugador, List<String> rutas, String cartaCrupier, List<String> cartaJugadores, boolean esPrimeravez,  int puntajeJugador, int PuntajeRival) {

    }

    @Override
    public void mostrarManoJugadorYdeCrupier(String manoDeJugador, String manoDeCrupier) {

    }

    @Override
    public void mostrarManoCrupier(String manodeCrupier,List<String> ruta) {

    }

    @Override
    public void procesarEntradaUsuario(String texto, Consumer<String> callback) {

    }

    @Override
    public void obtenerResultadoPartida(String texto, String NombreJugador, int puntajeJugador, int puntajeCrupier) {

    }

    @Override
    public boolean mostrarRecargar() {
        return false;
    }

    @Override
    public void mostrarRecargar(String nombreJugador, Consumer<Boolean> callback) {

    }

    @Override
    public void mostrarPuntajeSoloCrupierV(int puntajeCrupier) {

    }

    @Override
    public void mostrarManoJugadorYdeCrupier(String manojugadoor, String manocrupier, List<String> rutasImagenes, List<String> rutasImagenes1) {

    }

    @Override
    public String getMinombreVista() {
        return null;
    }
}
