/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p;

import Modelo.*;
import services.*;

import java.util.List;

/**
 *
 * @author lucci
 */
public class Ranking extends javax.swing.JFrame {

    /**
     * Creates new form Ranking
     */

    private Modelo.Ranking ranking; // instancia del modelo
    private Lobby lobby;
    public Ranking(Lobby volver) {
        lobby = volver;
        ranking = new Modelo.Ranking(); 
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana
        //No modificar el tamaño de la ventana:
        this.setResizable(false);



        // Inicializamos el TextArea con encabezado
        StringBuilder sb = new StringBuilder();
        sb.append("Lista De Ranking\n\n");

        //-------------------------------------------------------------------------------------------
        List<Jugador> listaRanking = ranking.obtenerRanking(); // obtenemos jugadores del archivo
        //HAcemos una busqueda para mostrar los jugdores de la lsita en el ranking
        if (listaRanking != null && !listaRanking.isEmpty()) {
            for (int i = 0; i < listaRanking.size(); i++) {
                Jugador j = listaRanking.get(i);
                //elimina si hay alguno en la lista menor a 25.
                if (j.getSaldo() < 25){
                    ranking.eliminarJugadorDeRanking(j.getNombre());
                }
                // Agregamos cada jugador al StringBuilder
                sb.append((i + 1) + ". " + j.getNombre() + " - Saldo: $" + j.getSaldo() + "\n");
            }
        } else {
            sb.append("No hay jugadores en el ranking.\n");
        }
        //-------------------------------------------------------------------------------------------



        // Mostramos todo en el TextArea
        this.textArea1.setText(sb.toString());





    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();
        button2 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textArea1.setBackground(new java.awt.Color(0, 0, 0));
        textArea1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        textArea1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Imagenes/mesa3.jpg"))); // NOI18N

        button2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        button2.setLabel("< Menu Principal");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        
        lobby.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
